on: release
name: 🚀 Deploy website on release
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
          
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ftp.cluster029.hosting.ovh.net
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        local-dir: "./release/"